# Generated by Django 3.1.4 on 2020-12-08 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20201208_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='member',
            new_name='created_by',
        ),
    ]
